### ISSUE TITLE
feat: Create authentication for the requests

### ISSUE THREAD

**Issue by MarioWork** [MarioWork/mcu-api#18]
### Todo
- [x]  Create fastify plugin for authentication
- [x] Decorate fastify instance with function that checks if the user is admin or normal user
- [x] Prevalidate the requests with that function
